let event_data = {
    "hackathon" : [
        {'start_time': "June 10 2022, 7PM",
        'end_time': "June 13 2022, 11AM" ,
        'participants': "4",
        'address': "100 Skyway Drive" ,
        'title': "OneHacks"},
        {'start_time': "June 10 2022, 7PM",
        'end_time': "June 13 2022, 11AM" ,
        'participants': "7",
        'address': "100 Skyway Drive" ,
        'title': "TwoHacks"},
        {'start_time': "June 10 2022, 7PM",
        'end_time': "June 13 2022, 11AM" ,
        'participants': "2",
        'address': "100 Skyway Drive" ,
        'title': "ThreeHacks"},
        {'start_time': "June 10 2022, 7PM",
        'end_time': "June 13 2022, 11AM" ,
        'participants': "5",
        'address': "100 Skyway Drive" ,
        'title': "FiveHacks"},
        {'start_time': "June 10 2022, 7PM",
        'end_time': "June 12 2022, 11AM" ,
        'participants': "10",
        'address': "100 Skyway Drive" ,
        'title': "TenHacks"},
    ],
    "soccer" : [
        {'start_time': "June 06 2022, 11AM",
        'end_time': "June 06 2022, 2PM" ,
        'participants': "1",
        'address': "Cataldi Park" ,
        'title': "Soccer @ Cataldi park"},
        {'start_time': "June 07 2022, 1PM",
        'end_time': "June 08 2022, 2PM" ,
        'participants': "3",
        'address': "132 Party Road" ,
        'title': "Soccer Party"},
        {'start_time': "May 2 2022, 11AM",
        'end_time': "August 12 2022, 2PM" ,
        'participants': "10",
        'address': "98 Sports Ave" ,
        'title': "Champions League"},
        {'start_time': "June 01 2022, 11AM",
        'end_time': "June 01, 2022, 2PM" ,
        'participants': "5",
        'address': "The Park" ,
        'title': "Soccer Game"},
        {'start_time': "June 03 2022, 1PM",
        'end_time': "June 03, 2022, 3PM" ,
        'participants': "3",
        'address': "Sunny Park" ,
        'title': "Soccer Practice"},
        {'start_time': "May 2 2022, 11AM",
        'end_time': "August 12 2022, 2PM" ,
        'participants': "10",
        'address': "98 Sports Ave" ,
        'title': "Soccer Camp"},
    ],
}




export default event_data;
